### ISSUE TITLE
ionic upload error : cannot read map of undefined

### ISSUE THREAD

**Issue by jainnikhil781gmailcom** [ionic-team/ionic-io-docs#12]
I started with new ionic 2 template project. installed node modules using npm install.

I want to build apk by using ionic.io so using ionic upload 

it gives error after sucessful login  cannot read map of undefined 

F:\diffionicapp\MyIonic2Project>ionic upload
WARN: No 'upload:before' gulp task found!
If your app requires a build step, you may want to ensure it runs before upload.

No previous login existed. Attempting to log in now.

To continue, please login to your Ionic account.
Don't have one? Create one at: https://apps.ionic.io/signup

Email: jain.nikhil781@gmail.com
Password:
Email or Password incorrect. Please visit https://apps.ionic.io for help.
Uploading app....
An error occurred uploading the build: TypeError: Cannot read property 'map' of undefined

TypeError: Cannot read property 'map' of undefined
    at Object.getDirectUploadKey (C:\Users\Nikhil\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\upload.js:262:18)
    at C:\Users\Nikhil\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\upload.js:40:21
    at _fulfilled (C:\Users\Nikhil\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:787:54)
    at self.promiseDispatch.done (C:\Users\Nikhil\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:816:30)
    at Promise.promise.promiseDispatch (C:\Users\Nikhil\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:749:13)
    at C:\Users\Nikhil\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:509:49
    at flush (C:\Users\Nikhil\AppData\Roaming\npm\node_modules\ionic\node_modules\q\q.js:108:17)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Cannot read property 'map' of undefined (CLI v2.0.0)

Your system information:

Cordova CLI: 6.3.1
Ionic Framework Version: 2.0.0-beta.11
Ionic CLI Version: 2.0.0
Ionic App Lib Version: 2.0.0
OS:
Node Version: v6.5.0

**Comment by morningcloud** [comment]
The issue is clear in the response message "Email or Password incorrect."

**Comment by dularion** [comment]
oh wow, because of the long stacktrace I didnt see the incorrect login. Could this be done more gracefully? Anyway, thanks @morningcloud
